pumukit_youtube:
    profiles:
        video_youtube:
            display: false
            wizard: false
            master: false
            tags: youtube html5
            target: PUCHYOUTUBE
            format: mp4
            codec: h264
            mime_type: 'video/x-mp4'
            extension: mp4
            resolution_hor: 0
            resolution_ver: 0
            bitrate: 1 Mbps
            framerate: 25
            channels: 1
            audio: true
            bat: |
                ffmpeg -loop 1 -i __IMAGE__ -i "{{input}}" -s 640x480 -c:v libx264 -c:a libfdk_aac -strict experimental -ar 44100 -b:a 128k -f mp4 -shortest "{{output}}"
            streamserver:
                name: Localhost
                type: download
                host: 127.0.0.1
                description: Local download server
                dir_out: "%pumukit.downloads_dir%"
                url_out: "%pumukit.downloads_url%"
            app: ffmpeg
            rel_duration_size: 1
            rel_duration_trans: 1
            downloadable: true
