<?php

namespace Pumukit\YoutubeBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AccountRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeAccountRepository extends DocumentRepository
{
}
